//frontend/src/editionAndDeletion/pages/deletionAccount/UIComponents/onfirmationModalUI/InitialConfirmationDeleteAcountUI.tsx

import CircleLoader from '../../../../../loader/circleLoader/CircleLoader';
import { currencyMinorUnit } from '../../../../../helpers/functions.ts';

import { RTAConfirmationModalPropsType } from './RTAConfirmationModal';

import './initialConfirmationDeleteAccountUI.css';

//TYPE DEFINITIONS
type InitialConfirmationDeleteAccountUIPropsType =
  RTAConfirmationModalPropsType & {
    buttonDisabled: boolean;
    // Generated by the dialog around this one, which is the element that
    // carries the role and therefore the element the heading has to name.
    titleId: string;
  };
//===================================
//UI COMPONENT
//InitialConfirmationDeleteAccountUI
//===================================
export const InitialConfirmationDeleteAccountUI = ({
  t,
  affectedAccountsReportCount = 0,
  pocketImpact = [],
  buttonDisabled = false,
  mainStatusFromParent = 'idle',
  onClose,
  onConfirm,
  message = '',
  titleId,
}: InitialConfirmationDeleteAccountUIPropsType) => {
  //RENDERING INITIAL CONFIRMATION SCREEN
  //Determine if showing error message
  const showErrorMessage =
    mainStatusFromParent === 'idle' &&
    message &&
    message !== t('clickToConfirm');

  //Determine button confirmation text
  const getConfirmationButtonText = () => {
    return affectedAccountsReportCount === 0
      ? t('confirmHardDelete')
      : t('confirmDeletion');
  };

  // RENDERING INITIAL CONFIRMATION SCREEN
  return (
    /* No role here any more. RTAConfirmationModal wraps this and declares
       itself the dialog, and a dialog nested in a dialog is not a structure a
       screen reader can report. This is that dialog's content. */
    <div className='confirm-delete-container fade-in '>
      {/* Title */}
      <h3 id={titleId} className='confirm-delete-title'>
        {t('title')}
      </h3>

      {/* Description */}
      <p className='confirm-delete-description '>{t('description')}</p>

      {/* Counter */}
      <p className='confirm-delete-count '>
        <span className='count-number'>{affectedAccountsReportCount}</span>
        <span className='affected-account'>{t('affectedAccounts')}</span>
      </p>

      {/* Pocket impact: named per POCKET_MODULE_SPEC.md §11.1 Q8b - the owner
          sees which pockets lose backing before confirming, since deleting
          this account removes their allocation rows in the same transaction. */}
      {pocketImpact.length > 0 && (
        <div className='pocket-impact-block'>
          <p className='pocket-impact-title'>{t('pocketImpactTitle')}</p>
          <ul className='pocket-impact-list'>
            {pocketImpact.map((row) => (
              <li key={row.pocketId} className='pocket-impact-row'>
                <span className='pocket-impact-name'>{row.pocketName}</span>
                <span className='pocket-impact-amount'>
                  {row.amountAllocated.toFixed(
                    currencyMinorUnit(row.currencyCode),
                  )}{' '}
                  {row.currencyCode}
                </span>
              </li>
            ))}
          </ul>
          <p className='pocket-impact-total'>
            {t('pocketImpactTotalLabel')}{' '}
            {pocketImpact
              .reduce((total, row) => total + row.amountAllocated, 0)
              .toFixed(currencyMinorUnit(pocketImpact[0].currencyCode))}{' '}
            {pocketImpact[0].currencyCode}
          </p>
          <p className='pocket-impact-note'>{t('pocketImpactNote')}</p>
        </div>
      )}

      {/* Processing Indicator */}
      {buttonDisabled && (
        <div className='processing-indicator' role='status' aria-live='polite'>
          <CircleLoader />
          <p>{message || t('processing')}</p>
        </div>
      )}

      {/* Error Message */}
      {showErrorMessage && (
        <div className='error-message' role='alert'>
          <strong>{t('apiError')}</strong>
          <span>{'message'} apiError</span>
        </div>
      )}

      {/* Action Buttons */}
      <div className={`action-buttons ${buttonDisabled ? 'disabled' : ''}`}>
        <button
          className='cancel-button'
          type='button'
          aria-label={t('cancel')}
          disabled={buttonDisabled}
          onClick={onClose}
        >
          {t('cancel')}
        </button>

        <button
          className='confirm-button'
          type='button'
          disabled={buttonDisabled}
          aria-label={getConfirmationButtonText()}
          onClick={onConfirm}
        >
          {getConfirmationButtonText()}
        </button>
      </div>
    </div>
  );
};

export default InitialConfirmationDeleteAccountUI;
