//frontend/src/pages/auth/AuthUI.tsx

/* ===============================
  🎭 AUTH UI ORCHESTRATOR
  Responsible for:
  - Toggle between SignIn and SignUp
  - Display global messages
  - Render the appropriate form component
  - Manage rememberMe state
 =============================== */
import { useEffect, useState } from 'react';
// import GoogleLogo from '../../../assets/auth/GoogleLogo';
import Logo from '../../../assets/logo.svg';
import SunIcon from '../../../assets/authSvg/SunSvg.svg';
import MoonIcon from '../../../assets/authSvg/MoonSvg.svg';
import Message, { MessageType } from '../formUIComponents/Message';
import { SignInFormDataType, SignUpFormDataType } from '../../validation/zod_schemas/authSchemas';
import SignInForm from '../signInForm/SignInForm';
import SignUpForm from '../signUpForm/SignUpForm';
import { getIdentity } from '../../auth_utils/localStorageHandle/authStorage'
import { useAuthUIStore } from '../../stores/useAuthUIStore';
import type { SignInResultType } from '../../hooks/useAuth';
import styles from './styles/authUI.module.css';

export type AuthUIPropsType = {
  // Resolves with the sign-in result: the form needs the failed one to render
  // the server's per-field validation messages.
  onSignIn: (credentials: SignInFormDataType, rememberMe: boolean) => Promise<SignInResultType>;
  onSignUp: (userData: SignUpFormDataType) => Promise<void>;
  isLoading: boolean;
  error: string | null;
  messageToUser?: string | null;
  isSignInInitial:boolean;
  clearError: () => void;
  onClose?: () => void;
  isDarkTheme: boolean;
  onToggleTheme: () => void;
  // Generated by useModalDialog and landed on the heading below, so the dialog
  // wrapping this component has something to be named by.
  titleId?: string;
  // Passed down to the active form, which reports whether it holds typed values.
  onDirtyChange?: (isDirty: boolean) => void;
  // Told which form is showing, so closing an empty form names it.
  onModeChange?: (isSignIn: boolean) => void;
};
//MAIN COMPONENT: AuthUI.tsx
function AuthUI({
  onSignIn,
  onSignUp,
  isLoading: externalLoading,
  error,
  messageToUser = '',
  isSignInInitial,
  clearError,
  onClose,
  isDarkTheme,
  onToggleTheme,
  titleId,
  onDirtyChange,
  onModeChange,
}: AuthUIPropsType): JSX.Element {
 //STATES
  const [isSignIn, setIsSignIn] = useState(isSignInInitial);
  const [rememberMe, setRememberMe] = useState(false);

 const [formKey, setFormKey] = useState(0); // ✅ For forced remount

  // The unsaved-changes guard lives in AuthModal, which also owns the backdrop
  // and Escape, so the Close button asks through the same confirm. The mode is
  // reported so an empty form's question names sign in or sign up.
  useEffect(() => {
   onModeChange?.(isSignIn);
  }, [isSignIn, onModeChange]);

  // ===============================
  // 🔄 REINITIALIZATION
  // ===============================
  useEffect(() => {
   if (isSignIn) {
     const identity = getIdentity();
     setRememberMe(identity?.rememberMe === true);
   }
  }, [isSignIn]);

  // ✅ Force form remount when toggling to ensure clean state
  const toggleAuthMode = () => {
    setIsSignIn(prev => !prev);
    setFormKey(prev => prev + 1); // Increment key to force remount
    clearError();
  };
 // ====================
 // 💬 BANNER MESSAGE
 // ====================
 const bannerMessage: { type: MessageType; text: string } | null = error
    ? { type: 'error', text: error }
    : messageToUser
    ? { type: 'success', text: messageToUser }
    : null;

// =============
// 🎨 RENDER
// =============
 return (
  <form autoComplete='off' className={styles['auth-container']}>
    {/* 🏷️ Header: brand mark on the left, closing on the right */}
    <div className={styles['auth-header']}>
      {/* The svg module is typed as taking no props, so the class rides on a
          wrapper rather than on the mark itself. */}
      <span className={styles['auth-header__logo']} aria-hidden='true'>
        <Logo />
      </span>

      <div className={styles['auth-header__controls']}>
        <button
          type='button'
          onClick={onToggleTheme}
          className={styles.themeToggle}
          aria-label={isDarkTheme ? 'Switch to light theme' : 'Switch to dark theme'}
        >
          {isDarkTheme ? <SunIcon /> : <MoonIcon />}
        </button>

        {onClose && (
          <button
            type='button'
            onClick={onClose}
            className={styles.closeButton}
          >
            <span>Close</span>
          </button>
        )}
      </div>
    </div>

    <div className={styles['auth-header__rule']} />

    {/* 📢 Message Area with close button */}
    <div
      className={`${styles.messageArea} ${
        bannerMessage ? styles.isVisible : styles.isHidden
      }`}
    >
      {bannerMessage && (
      <Message
        type={bannerMessage.type}
        message={bannerMessage.text}
        autoDismiss={5000}
        onDismiss={() => {
          clearError();//clean store errors
          if (bannerMessage.type === 'success') {
           useAuthUIStore.getState().setMessage(null);
          }
        }}
        showIcon={false}
      />
      )}
    </div>

    {/* The heading is read, not seen: the submit button and the toggle link
        below both name the mode. It stays in the tree so the dialog has one. */}
    <h2 id={titleId} className={styles['auth-container__title']}>
      {isSignIn ? 'Sign In' : 'Sign Up'}
    </h2>

    <p className={styles['auth-container__note']}>All fields are required</p>

    {/* Conditional Form Rendering */}
    {isSignIn ? (
      <SignInForm
       key={`signin-${formKey}`}
        onSignIn={onSignIn}
        externalLoading={externalLoading}
        error={error}
        clearError={clearError}
        rememberMe={rememberMe}
        setRememberMe={setRememberMe}
        onDirtyChange={onDirtyChange}
      />
    ) : (
      <SignUpForm
        key={`signup-${formKey}`}
        onSignUp={onSignUp}
        externalLoading={externalLoading}
        error={error}
        clearError={clearError}
        onDirtyChange={onDirtyChange}
      />
    )}

    {/* Footer Actions */}
    <div className={styles['auth-actions']}>
      <button
        type="button"
        className={styles['auth-actions__toggle-button']}
        onClick={toggleAuthMode}
        disabled={externalLoading}
      >
        {isSignIn
          ? <>Don't have an account? <span className={styles['auth-actions__toggle-action']}>Sign up</span></>
          : <>Already have an account? <span className={styles['auth-actions__toggle-action']}>Sign in</span></>}
      </button>

      {/* Closing moved to the header, where it aligns with the brand mark and
          sits inside the panel it closes. */}

      {/* Google Sign-In Placeholder */}
      {/* <div className={styles.socialSection}>
        <div className={styles.separator}>
          <span>OR</span>
        </div>
        <button type="button" className={styles['google-signin-button']} disabled>
          <GoogleLogo size={20} />
          Continue with Google
        </button>
      </div> */}
    </div>
  </form>
 );
}

export default AuthUI;