// export const BASE_URL: string = import.meta.env.VITE_API_URL;
// export const url_debtors = BASE_URL + '/' + 'debtors';
// export const url_debtors_debt = BASE_URL + '/' + 'debtors/debt';
// export const url_categories = BASE_URL + '/' + 'categories';
// export const url_investment = BASE_URL + '/' + 'investment';
// export const url_sources = BASE_URL + '/' + 'sources';
// export const url_budget = BASE_URL + '/' + 'budget';
// export const url_accounts = BASE_URL + '/' + 'accounts'; //expense and income accounts are the same
// export const url_investment_acc = BASE_URL + '/' + 'investment-accounts'; //not implemented yet
